### ISSUE TITLE
"40% of industrial capacity is idle"

### ISSUE THREAD

**Issue by toonsevrin** [mhingston/Netonomy#1]
What do you mean by the claim that 40% of the industrial capacity is idle, and that this can be increased to 80%? You wrote it at https://github.com/mhingston/Netonomy#collaborative-consumption.

+ could you provide a reference for this claim?

**Comment by mhingston** [comment]
Hi @toonsevrin 

That quote was taken from [Chapter 2](http://sacred-economics.com/sacred-economics-chapter-2-the-illusion-of-scarcity/) of Sacred Economics by Charles Eisenstein.

> On my street, every family possesses a lawnmower that is used perhaps ten hours per summer. Each kitchen has a blender that is used at most fifteen minutes per week. At any given moment, about half the cars are parked on the street, doing nothing. Most families have their own hedge clippers, their own power tools, their own exercise equipment. Because they are unused most of the time, most of these things are superfluous. Our quality of life would be just as high with half the number of cars, a tenth of the lawnmowers, and two or three Stairmasters for the whole street. In fact, it would be higher since we would have occasion to interact and share.(6) Even at our current, gratuitously high rate of consumption, **some 40 percent of the world’s industrial capacity stands idle. That figure could be increased to 80 percent or more without any loss of human happiness.** All we would lose would be the pollution and tedium of a lot of factory production. Of course, we would lose a vast number of “jobs” as well, but since these are not contributing much to human well-being anyway, we could employ those people digging holes in the ground and filling them up again with no loss. Or, better, we could devote them to labor-intensive roles like permaculture, care for the sick and elderly, restoration of ecosystems, and all the other needs of today that go tragically unmet for lack of money.

I believe what Charles is suggesting is that if industrial production were organised in such a way that the factors of production were utilised 100% of the time then we could maintain the same level of industrial output with just 20% of the capacity. I couldn't find a reference for his assertion but I imagine there are a large number of assumptions built-in to that scenario.

**Comment by toonsevrin** [comment]
Thanks for the reference (and posting your blog on this repo)! 

And indeed, he makes quite a few assumptions, but I like the thought experiment.  

Btw, apps like BlaBlaCar show that this is possible for cars (sucks there's no blender-sharing app yet).
